import { EmployerProfilesService } from './employer-profiles.service';
import { CreateEmployerProfileDto } from './dto/create-employer-profile.dto';
import { UpdateEmployerProfileDto } from './dto/update-employer-profile.dto';
import { CreateEmployerCategoryDto } from './dto/create-employer-category.dto';
import type { AuthenticatedRequest } from '../../common/types/auth-request.type';
export declare class EmployerProfilesController {
    private readonly employerProfilesService;
    constructor(employerProfilesService: EmployerProfilesService);
    createProfile(req: AuthenticatedRequest, dto: CreateEmployerProfileDto): Promise<{
        isVerified: boolean;
        categories: import("../../entities/master").JobCategory[];
        id: string;
        user: import("../users/user.entity").User;
        companyName: string;
        industry: import("../../entities/master").Industry;
        location: string;
        contactEmail: string;
        avatarUrl: string | null;
        about: string | null;
        companySize: string | null;
        foundedAt: Date | null;
        website: string | null;
        phone: string | null;
        currentPlanType: string;
        jobPostLimit: number;
        createdAt: Date;
        updatedAt: Date;
        jobs: import("../jobs/job.entity").Job[];
        reviews: import("../reviews/employer-review.entity").EmployerReview[];
        payments: import("../payments/payment.entity").Payment[];
    }>;
    getMyProfile(req: AuthenticatedRequest): Promise<{
        isVerified: boolean;
        categories: import("../../entities/master").JobCategory[];
        id: string;
        user: import("../users/user.entity").User;
        companyName: string;
        industry: import("../../entities/master").Industry;
        location: string;
        contactEmail: string;
        avatarUrl: string | null;
        about: string | null;
        companySize: string | null;
        foundedAt: Date | null;
        website: string | null;
        phone: string | null;
        currentPlanType: string;
        jobPostLimit: number;
        createdAt: Date;
        updatedAt: Date;
        jobs: import("../jobs/job.entity").Job[];
        reviews: import("../reviews/employer-review.entity").EmployerReview[];
        payments: import("../payments/payment.entity").Payment[];
    }>;
    getMyCategories(req: AuthenticatedRequest): Promise<import("../../entities/master").JobCategory[]>;
    createMyCategory(req: AuthenticatedRequest, dto: CreateEmployerCategoryDto): Promise<import("../../entities/master").JobCategory>;
    deleteMyCategory(req: AuthenticatedRequest, id: string): Promise<{
        message: string;
    }>;
    getProfileById(id: string): Promise<{
        isVerified: boolean;
        categories: import("../../entities/master").JobCategory[];
        id: string;
        user: import("../users/user.entity").User;
        companyName: string;
        industry: import("../../entities/master").Industry;
        location: string;
        contactEmail: string;
        avatarUrl: string | null;
        about: string | null;
        companySize: string | null;
        foundedAt: Date | null;
        website: string | null;
        phone: string | null;
        currentPlanType: string;
        jobPostLimit: number;
        createdAt: Date;
        updatedAt: Date;
        jobs: import("../jobs/job.entity").Job[];
        reviews: import("../reviews/employer-review.entity").EmployerReview[];
        payments: import("../payments/payment.entity").Payment[];
    }>;
    updateMyProfile(req: AuthenticatedRequest, dto: UpdateEmployerProfileDto): Promise<{
        isVerified: boolean;
        categories: import("../../entities/master").JobCategory[];
        id: string;
        user: import("../users/user.entity").User;
        companyName: string;
        industry: import("../../entities/master").Industry;
        location: string;
        contactEmail: string;
        avatarUrl: string | null;
        about: string | null;
        companySize: string | null;
        foundedAt: Date | null;
        website: string | null;
        phone: string | null;
        currentPlanType: string;
        jobPostLimit: number;
        createdAt: Date;
        updatedAt: Date;
        jobs: import("../jobs/job.entity").Job[];
        reviews: import("../reviews/employer-review.entity").EmployerReview[];
        payments: import("../payments/payment.entity").Payment[];
    }>;
    updateProfile(req: AuthenticatedRequest, dto: UpdateEmployerProfileDto): Promise<{
        isVerified: boolean;
        categories: import("../../entities/master").JobCategory[];
        id: string;
        user: import("../users/user.entity").User;
        companyName: string;
        industry: import("../../entities/master").Industry;
        location: string;
        contactEmail: string;
        avatarUrl: string | null;
        about: string | null;
        companySize: string | null;
        foundedAt: Date | null;
        website: string | null;
        phone: string | null;
        currentPlanType: string;
        jobPostLimit: number;
        createdAt: Date;
        updatedAt: Date;
        jobs: import("../jobs/job.entity").Job[];
        reviews: import("../reviews/employer-review.entity").EmployerReview[];
        payments: import("../payments/payment.entity").Payment[];
    }>;
    deleteProfile(req: AuthenticatedRequest): Promise<{
        message: string;
    }>;
}
