import { Repository } from 'typeorm';
import { EmployerProfile } from './employer-profile.entity';
import { CreateEmployerProfileDto } from './dto/create-employer-profile.dto';
import { UpdateEmployerProfileDto } from './dto/update-employer-profile.dto';
import { CreateEmployerCategoryDto } from './dto/create-employer-category.dto';
import { User } from '../users/user.entity';
import { Industry } from '../../entities/master/industry.entity';
import { JobCategory } from '../../entities/master/job-category.entity';
export declare class EmployerProfilesService {
    private employerProfileRepository;
    private userRepository;
    private industryRepository;
    private jobCategoryRepository;
    constructor(employerProfileRepository: Repository<EmployerProfile>, userRepository: Repository<User>, industryRepository: Repository<Industry>, jobCategoryRepository: Repository<JobCategory>);
    create(userId: string, dto: CreateEmployerProfileDto): Promise<{
        isVerified: boolean;
        categories: JobCategory[];
        id: string;
        user: User;
        companyName: string;
        industry: Industry;
        location: string;
        contactEmail: string;
        avatarUrl: string | null;
        about: string | null;
        companySize: string | null;
        foundedAt: Date | null;
        website: string | null;
        phone: string | null;
        currentPlanType: string;
        jobPostLimit: number;
        createdAt: Date;
        updatedAt: Date;
        jobs: import("../jobs/job.entity").Job[];
        reviews: import("../reviews/employer-review.entity").EmployerReview[];
        payments: import("../payments/payment.entity").Payment[];
    }>;
    findByUserId(userId: string): Promise<{
        isVerified: boolean;
        categories: JobCategory[];
        id: string;
        user: User;
        companyName: string;
        industry: Industry;
        location: string;
        contactEmail: string;
        avatarUrl: string | null;
        about: string | null;
        companySize: string | null;
        foundedAt: Date | null;
        website: string | null;
        phone: string | null;
        currentPlanType: string;
        jobPostLimit: number;
        createdAt: Date;
        updatedAt: Date;
        jobs: import("../jobs/job.entity").Job[];
        reviews: import("../reviews/employer-review.entity").EmployerReview[];
        payments: import("../payments/payment.entity").Payment[];
    }>;
    findById(id: string): Promise<{
        isVerified: boolean;
        categories: JobCategory[];
        id: string;
        user: User;
        companyName: string;
        industry: Industry;
        location: string;
        contactEmail: string;
        avatarUrl: string | null;
        about: string | null;
        companySize: string | null;
        foundedAt: Date | null;
        website: string | null;
        phone: string | null;
        currentPlanType: string;
        jobPostLimit: number;
        createdAt: Date;
        updatedAt: Date;
        jobs: import("../jobs/job.entity").Job[];
        reviews: import("../reviews/employer-review.entity").EmployerReview[];
        payments: import("../payments/payment.entity").Payment[];
    }>;
    update(userId: string, dto: UpdateEmployerProfileDto): Promise<{
        isVerified: boolean;
        categories: JobCategory[];
        id: string;
        user: User;
        companyName: string;
        industry: Industry;
        location: string;
        contactEmail: string;
        avatarUrl: string | null;
        about: string | null;
        companySize: string | null;
        foundedAt: Date | null;
        website: string | null;
        phone: string | null;
        currentPlanType: string;
        jobPostLimit: number;
        createdAt: Date;
        updatedAt: Date;
        jobs: import("../jobs/job.entity").Job[];
        reviews: import("../reviews/employer-review.entity").EmployerReview[];
        payments: import("../payments/payment.entity").Payment[];
    }>;
    delete(userId: string): Promise<{
        message: string;
    }>;
    getCategories(userId: string): Promise<JobCategory[]>;
    createCategory(userId: string, dto: CreateEmployerCategoryDto): Promise<JobCategory>;
    deleteCategory(userId: string, categoryId: string): Promise<{
        message: string;
    }>;
    private findEntityByUserId;
    private withJobCategories;
}
