import { EmployerProfile } from '../employer-profiles/employer-profile.entity';
import { JobCategory } from '../../entities/master/job-category.entity';
import { JobType } from '../../entities/master/job-type.entity';
import { JobStatus } from '../../entities/master/job-status.entity';
import { Application } from '../applications/application.entity';
import { JobView } from './job-view.entity';
import { SavedJob } from './saved-job.entity';
import { JobSkill } from './job-skill.entity';
import { Report } from '../reports/report.entity';
import { JobHistory } from './job-history.entity';
import { JobApprovalStatus } from './job-approval-status.enum';
export declare class Job {
    id: string;
    employer: EmployerProfile;
    category: JobCategory;
    jobType: JobType;
    title: string;
    description: string;
    summary: string;
    benefits: string;
    imageUrl: string;
    location: string;
    latitude: number;
    longitude: number;
    salaryMin: number;
    salaryMax: number;
    currency: string;
    numberOfOpenings: number;
    deadline: Date;
    requirements: string;
    is_blocked: boolean;
    status: JobStatus;
    approvalStatus: JobApprovalStatus;
    rejectionReason: string | null;
    createdAt: Date;
    updatedAt: Date;
    applications: Application[];
    views: JobView[];
    savedBy: SavedJob[];
    jobSkills: JobSkill[];
    reports: Report[];
    history: JobHistory[];
}
