import { JobsService } from './jobs.service';
import { CreateJobDto } from './dto/create-job.dto';
import { UpdateJobDto } from './dto/update-job.dto';
import { UpdateJobStatusDto } from './dto/update-job-status.dto';
import { JobSearchDto } from './dto/search-job.dto';
import { PaginationDto } from './dto/pagination-job.dto';
import type { AuthenticatedRequest } from '../../common/types/auth-request.type';
import type { Response } from 'express';
export declare class JobsController {
    private readonly jobsService;
    constructor(jobsService: JobsService);
    getAllJobs(paginationDto: PaginationDto): Promise<{
        data: {
            isExpired: boolean;
            id: string;
            employer: import("../employer-profiles/employer-profile.entity").EmployerProfile;
            category: import("../../entities/master").JobCategory;
            jobType: import("../../entities/master").JobType;
            title: string;
            description: string;
            summary: string;
            benefits: string;
            imageUrl: string;
            location: string;
            latitude: number;
            longitude: number;
            salaryMin: number;
            salaryMax: number;
            currency: string;
            numberOfOpenings: number;
            deadline: Date;
            requirements: string;
            is_blocked: boolean;
            status: import("../../entities/master").JobStatus;
            approvalStatus: import("./job-approval-status.enum").JobApprovalStatus;
            rejectionReason: string | null;
            createdAt: Date;
            updatedAt: Date;
            applications: import("../applications/application.entity").Application[];
            views: import("./job-view.entity").JobView[];
            savedBy: import("./saved-job.entity").SavedJob[];
            jobSkills: import("./job-skill.entity").JobSkill[];
            reports: import("../reports/report.entity").Report[];
            history: import("./job-history.entity").JobHistory[];
        }[];
        meta: {
            totalItems: number;
            itemCount: number;
            itemsPerPage: number;
            totalPages: number;
            currentPage: number;
        };
    }>;
    getMyPostedJobs(req: AuthenticatedRequest): Promise<{
        isExpired: boolean;
        id: string;
        employer: import("../employer-profiles/employer-profile.entity").EmployerProfile;
        category: import("../../entities/master").JobCategory;
        jobType: import("../../entities/master").JobType;
        title: string;
        description: string;
        summary: string;
        benefits: string;
        imageUrl: string;
        location: string;
        latitude: number;
        longitude: number;
        salaryMin: number;
        salaryMax: number;
        currency: string;
        numberOfOpenings: number;
        deadline: Date;
        requirements: string;
        is_blocked: boolean;
        status: import("../../entities/master").JobStatus;
        approvalStatus: import("./job-approval-status.enum").JobApprovalStatus;
        rejectionReason: string | null;
        createdAt: Date;
        updatedAt: Date;
        applications: import("../applications/application.entity").Application[];
        views: import("./job-view.entity").JobView[];
        savedBy: import("./saved-job.entity").SavedJob[];
        jobSkills: import("./job-skill.entity").JobSkill[];
        reports: import("../reports/report.entity").Report[];
        history: import("./job-history.entity").JobHistory[];
    }[]>;
    getMyPostedJobById(req: AuthenticatedRequest, id: string): Promise<{
        isExpired: boolean;
        id: string;
        employer: import("../employer-profiles/employer-profile.entity").EmployerProfile;
        category: import("../../entities/master").JobCategory;
        jobType: import("../../entities/master").JobType;
        title: string;
        description: string;
        summary: string;
        benefits: string;
        imageUrl: string;
        location: string;
        latitude: number;
        longitude: number;
        salaryMin: number;
        salaryMax: number;
        currency: string;
        numberOfOpenings: number;
        deadline: Date;
        requirements: string;
        is_blocked: boolean;
        status: import("../../entities/master").JobStatus;
        approvalStatus: import("./job-approval-status.enum").JobApprovalStatus;
        rejectionReason: string | null;
        createdAt: Date;
        updatedAt: Date;
        applications: import("../applications/application.entity").Application[];
        views: import("./job-view.entity").JobView[];
        savedBy: import("./saved-job.entity").SavedJob[];
        jobSkills: import("./job-skill.entity").JobSkill[];
        reports: import("../reports/report.entity").Report[];
        history: import("./job-history.entity").JobHistory[];
    }>;
    getMatchBySkills(req: AuthenticatedRequest): Promise<import("./job.entity").Job[]>;
    getMatchByMajor(req: AuthenticatedRequest): Promise<import("./job.entity").Job[]>;
    getRecommendedJobs(req: AuthenticatedRequest): Promise<import("./job.entity").Job[] | {
        data: {
            isExpired: boolean;
            id: string;
            employer: import("../employer-profiles/employer-profile.entity").EmployerProfile;
            category: import("../../entities/master").JobCategory;
            jobType: import("../../entities/master").JobType;
            title: string;
            description: string;
            summary: string;
            benefits: string;
            imageUrl: string;
            location: string;
            latitude: number;
            longitude: number;
            salaryMin: number;
            salaryMax: number;
            currency: string;
            numberOfOpenings: number;
            deadline: Date;
            requirements: string;
            is_blocked: boolean;
            status: import("../../entities/master").JobStatus;
            approvalStatus: import("./job-approval-status.enum").JobApprovalStatus;
            rejectionReason: string | null;
            createdAt: Date;
            updatedAt: Date;
            applications: import("../applications/application.entity").Application[];
            views: import("./job-view.entity").JobView[];
            savedBy: import("./saved-job.entity").SavedJob[];
            jobSkills: import("./job-skill.entity").JobSkill[];
            reports: import("../reports/report.entity").Report[];
            history: import("./job-history.entity").JobHistory[];
        }[];
        meta: {
            totalItems: number;
            itemCount: number;
            itemsPerPage: number;
            totalPages: number;
            currentPage: number;
        };
    }>;
    searchJobs(query: JobSearchDto): Promise<{
        data: {
            isExpired: boolean;
            id: string;
            employer: import("../employer-profiles/employer-profile.entity").EmployerProfile;
            category: import("../../entities/master").JobCategory;
            jobType: import("../../entities/master").JobType;
            title: string;
            description: string;
            summary: string;
            benefits: string;
            imageUrl: string;
            location: string;
            latitude: number;
            longitude: number;
            salaryMin: number;
            salaryMax: number;
            currency: string;
            numberOfOpenings: number;
            deadline: Date;
            requirements: string;
            is_blocked: boolean;
            status: import("../../entities/master").JobStatus;
            approvalStatus: import("./job-approval-status.enum").JobApprovalStatus;
            rejectionReason: string | null;
            createdAt: Date;
            updatedAt: Date;
            applications: import("../applications/application.entity").Application[];
            views: import("./job-view.entity").JobView[];
            savedBy: import("./saved-job.entity").SavedJob[];
            jobSkills: import("./job-skill.entity").JobSkill[];
            reports: import("../reports/report.entity").Report[];
            history: import("./job-history.entity").JobHistory[];
        }[];
        meta: {
            totalItems: number;
            itemCount: number;
            itemsPerPage: number;
            totalPages: number;
            currentPage: number;
        };
    }>;
    getJobCategories(): Promise<import("../../entities/master").JobCategory[]>;
    getAllJobsForAdmin(paginationDto: PaginationDto): Promise<{
        data: {
            isExpired: boolean;
            id: string;
            employer: import("../employer-profiles/employer-profile.entity").EmployerProfile;
            category: import("../../entities/master").JobCategory;
            jobType: import("../../entities/master").JobType;
            title: string;
            description: string;
            summary: string;
            benefits: string;
            imageUrl: string;
            location: string;
            latitude: number;
            longitude: number;
            salaryMin: number;
            salaryMax: number;
            currency: string;
            numberOfOpenings: number;
            deadline: Date;
            requirements: string;
            is_blocked: boolean;
            status: import("../../entities/master").JobStatus;
            approvalStatus: import("./job-approval-status.enum").JobApprovalStatus;
            rejectionReason: string | null;
            createdAt: Date;
            updatedAt: Date;
            applications: import("../applications/application.entity").Application[];
            views: import("./job-view.entity").JobView[];
            savedBy: import("./saved-job.entity").SavedJob[];
            jobSkills: import("./job-skill.entity").JobSkill[];
            reports: import("../reports/report.entity").Report[];
            history: import("./job-history.entity").JobHistory[];
        }[];
        meta: {
            totalItems: number;
            itemCount: number;
            itemsPerPage: number;
            totalPages: number;
            currentPage: number;
        };
    }>;
    searchJobsForAdmin(query: JobSearchDto): Promise<{
        data: {
            isExpired: boolean;
            id: string;
            employer: import("../employer-profiles/employer-profile.entity").EmployerProfile;
            category: import("../../entities/master").JobCategory;
            jobType: import("../../entities/master").JobType;
            title: string;
            description: string;
            summary: string;
            benefits: string;
            imageUrl: string;
            location: string;
            latitude: number;
            longitude: number;
            salaryMin: number;
            salaryMax: number;
            currency: string;
            numberOfOpenings: number;
            deadline: Date;
            requirements: string;
            is_blocked: boolean;
            status: import("../../entities/master").JobStatus;
            approvalStatus: import("./job-approval-status.enum").JobApprovalStatus;
            rejectionReason: string | null;
            createdAt: Date;
            updatedAt: Date;
            applications: import("../applications/application.entity").Application[];
            views: import("./job-view.entity").JobView[];
            savedBy: import("./saved-job.entity").SavedJob[];
            jobSkills: import("./job-skill.entity").JobSkill[];
            reports: import("../reports/report.entity").Report[];
            history: import("./job-history.entity").JobHistory[];
        }[];
        meta: {
            totalItems: number;
            itemCount: number;
            itemsPerPage: number;
            totalPages: number;
            currentPage: number;
        };
    }>;
    exportJobsForAdmin(query: JobSearchDto, res: Response): Promise<void>;
    getJobByIdForAdmin(id: string): Promise<{
        isExpired: boolean;
        id: string;
        employer: import("../employer-profiles/employer-profile.entity").EmployerProfile;
        category: import("../../entities/master").JobCategory;
        jobType: import("../../entities/master").JobType;
        title: string;
        description: string;
        summary: string;
        benefits: string;
        imageUrl: string;
        location: string;
        latitude: number;
        longitude: number;
        salaryMin: number;
        salaryMax: number;
        currency: string;
        numberOfOpenings: number;
        deadline: Date;
        requirements: string;
        is_blocked: boolean;
        status: import("../../entities/master").JobStatus;
        approvalStatus: import("./job-approval-status.enum").JobApprovalStatus;
        rejectionReason: string | null;
        createdAt: Date;
        updatedAt: Date;
        applications: import("../applications/application.entity").Application[];
        views: import("./job-view.entity").JobView[];
        savedBy: import("./saved-job.entity").SavedJob[];
        jobSkills: import("./job-skill.entity").JobSkill[];
        reports: import("../reports/report.entity").Report[];
        history: import("./job-history.entity").JobHistory[];
    }>;
    getJobById(id: string): Promise<{
        isExpired: boolean;
        id: string;
        employer: import("../employer-profiles/employer-profile.entity").EmployerProfile;
        category: import("../../entities/master").JobCategory;
        jobType: import("../../entities/master").JobType;
        title: string;
        description: string;
        summary: string;
        benefits: string;
        imageUrl: string;
        location: string;
        latitude: number;
        longitude: number;
        salaryMin: number;
        salaryMax: number;
        currency: string;
        numberOfOpenings: number;
        deadline: Date;
        requirements: string;
        is_blocked: boolean;
        status: import("../../entities/master").JobStatus;
        approvalStatus: import("./job-approval-status.enum").JobApprovalStatus;
        rejectionReason: string | null;
        createdAt: Date;
        updatedAt: Date;
        applications: import("../applications/application.entity").Application[];
        views: import("./job-view.entity").JobView[];
        savedBy: import("./saved-job.entity").SavedJob[];
        jobSkills: import("./job-skill.entity").JobSkill[];
        reports: import("../reports/report.entity").Report[];
        history: import("./job-history.entity").JobHistory[];
    }>;
    createJob(req: AuthenticatedRequest, dto: CreateJobDto): Promise<import("./job.entity").Job>;
    updateJob(req: AuthenticatedRequest, id: string, dto: UpdateJobDto): Promise<import("./job.entity").Job | null>;
    updateJobStatus(req: AuthenticatedRequest, id: string, dto: UpdateJobStatusDto): Promise<import("./job.entity").Job | null>;
    deleteJob(req: AuthenticatedRequest, id: string): Promise<{
        message: string;
    }>;
    blockJob(id: string): Promise<import("./job.entity").Job>;
    unblockJob(id: string): Promise<import("./job.entity").Job>;
}
