import { Repository } from 'typeorm';
import { Job } from './job.entity';
import { JobApprovalStatus } from './job-approval-status.enum';
import { CreateJobDto } from './dto/create-job.dto';
import { UpdateJobDto } from './dto/update-job.dto';
import { UpdateJobStatusDto } from './dto/update-job-status.dto';
import { EmployerProfile } from '../employer-profiles/employer-profile.entity';
import { JobCategory } from '../../entities/master/job-category.entity';
import { JobType } from '../../entities/master/job-type.entity';
import { JobStatus } from '../../entities/master/job-status.entity';
import { JobHistory } from './job-history.entity';
import { JobSearchDto } from './dto/search-job.dto';
import { StudentProfile } from '../student-profiles/student-profile.entity';
import { PaginationDto } from './dto/pagination-job.dto';
export declare class JobsService {
    private jobRepository;
    private employerProfileRepository;
    private jobCategoryRepository;
    private jobTypeRepository;
    private jobStatusRepository;
    private jobHistoryRepository;
    private studentProfileRepository;
    constructor(jobRepository: Repository<Job>, employerProfileRepository: Repository<EmployerProfile>, jobCategoryRepository: Repository<JobCategory>, jobTypeRepository: Repository<JobType>, jobStatusRepository: Repository<JobStatus>, jobHistoryRepository: Repository<JobHistory>, studentProfileRepository: Repository<StudentProfile>);
    private escapeCsvValue;
    getAllJobs(paginationDto: PaginationDto): Promise<{
        data: {
            isExpired: boolean;
            id: string;
            employer: EmployerProfile;
            category: JobCategory;
            jobType: JobType;
            title: string;
            description: string;
            summary: string;
            benefits: string;
            imageUrl: string;
            location: string;
            latitude: number;
            longitude: number;
            salaryMin: number;
            salaryMax: number;
            currency: string;
            numberOfOpenings: number;
            deadline: Date;
            requirements: string;
            is_blocked: boolean;
            status: JobStatus;
            approvalStatus: JobApprovalStatus;
            rejectionReason: string | null;
            createdAt: Date;
            updatedAt: Date;
            applications: import("../applications/application.entity").Application[];
            views: import("./job-view.entity").JobView[];
            savedBy: import("./saved-job.entity").SavedJob[];
            jobSkills: import("./job-skill.entity").JobSkill[];
            reports: import("../reports/report.entity").Report[];
            history: JobHistory[];
        }[];
        meta: {
            totalItems: number;
            itemCount: number;
            itemsPerPage: number;
            totalPages: number;
            currentPage: number;
        };
    }>;
    getAllJobsForAdmin(paginationDto: PaginationDto): Promise<{
        data: {
            isExpired: boolean;
            id: string;
            employer: EmployerProfile;
            category: JobCategory;
            jobType: JobType;
            title: string;
            description: string;
            summary: string;
            benefits: string;
            imageUrl: string;
            location: string;
            latitude: number;
            longitude: number;
            salaryMin: number;
            salaryMax: number;
            currency: string;
            numberOfOpenings: number;
            deadline: Date;
            requirements: string;
            is_blocked: boolean;
            status: JobStatus;
            approvalStatus: JobApprovalStatus;
            rejectionReason: string | null;
            createdAt: Date;
            updatedAt: Date;
            applications: import("../applications/application.entity").Application[];
            views: import("./job-view.entity").JobView[];
            savedBy: import("./saved-job.entity").SavedJob[];
            jobSkills: import("./job-skill.entity").JobSkill[];
            reports: import("../reports/report.entity").Report[];
            history: JobHistory[];
        }[];
        meta: {
            totalItems: number;
            itemCount: number;
            itemsPerPage: number;
            totalPages: number;
            currentPage: number;
        };
    }>;
    setJobBlocked(id: string, blocked: boolean): Promise<Job>;
    getJobByIdForAdmin(id: string): Promise<{
        isExpired: boolean;
        id: string;
        employer: EmployerProfile;
        category: JobCategory;
        jobType: JobType;
        title: string;
        description: string;
        summary: string;
        benefits: string;
        imageUrl: string;
        location: string;
        latitude: number;
        longitude: number;
        salaryMin: number;
        salaryMax: number;
        currency: string;
        numberOfOpenings: number;
        deadline: Date;
        requirements: string;
        is_blocked: boolean;
        status: JobStatus;
        approvalStatus: JobApprovalStatus;
        rejectionReason: string | null;
        createdAt: Date;
        updatedAt: Date;
        applications: import("../applications/application.entity").Application[];
        views: import("./job-view.entity").JobView[];
        savedBy: import("./saved-job.entity").SavedJob[];
        jobSkills: import("./job-skill.entity").JobSkill[];
        reports: import("../reports/report.entity").Report[];
        history: JobHistory[];
    }>;
    getJobCategories(): Promise<JobCategory[]>;
    getJobById(id: string): Promise<{
        isExpired: boolean;
        id: string;
        employer: EmployerProfile;
        category: JobCategory;
        jobType: JobType;
        title: string;
        description: string;
        summary: string;
        benefits: string;
        imageUrl: string;
        location: string;
        latitude: number;
        longitude: number;
        salaryMin: number;
        salaryMax: number;
        currency: string;
        numberOfOpenings: number;
        deadline: Date;
        requirements: string;
        is_blocked: boolean;
        status: JobStatus;
        approvalStatus: JobApprovalStatus;
        rejectionReason: string | null;
        createdAt: Date;
        updatedAt: Date;
        applications: import("../applications/application.entity").Application[];
        views: import("./job-view.entity").JobView[];
        savedBy: import("./saved-job.entity").SavedJob[];
        jobSkills: import("./job-skill.entity").JobSkill[];
        reports: import("../reports/report.entity").Report[];
        history: JobHistory[];
    }>;
    createJob(userId: string, dto: CreateJobDto): Promise<Job>;
    getMyPostedJobs(userId: string): Promise<{
        isExpired: boolean;
        id: string;
        employer: EmployerProfile;
        category: JobCategory;
        jobType: JobType;
        title: string;
        description: string;
        summary: string;
        benefits: string;
        imageUrl: string;
        location: string;
        latitude: number;
        longitude: number;
        salaryMin: number;
        salaryMax: number;
        currency: string;
        numberOfOpenings: number;
        deadline: Date;
        requirements: string;
        is_blocked: boolean;
        status: JobStatus;
        approvalStatus: JobApprovalStatus;
        rejectionReason: string | null;
        createdAt: Date;
        updatedAt: Date;
        applications: import("../applications/application.entity").Application[];
        views: import("./job-view.entity").JobView[];
        savedBy: import("./saved-job.entity").SavedJob[];
        jobSkills: import("./job-skill.entity").JobSkill[];
        reports: import("../reports/report.entity").Report[];
        history: JobHistory[];
    }[]>;
    getMyPostedJobById(userId: string, id: string): Promise<{
        isExpired: boolean;
        id: string;
        employer: EmployerProfile;
        category: JobCategory;
        jobType: JobType;
        title: string;
        description: string;
        summary: string;
        benefits: string;
        imageUrl: string;
        location: string;
        latitude: number;
        longitude: number;
        salaryMin: number;
        salaryMax: number;
        currency: string;
        numberOfOpenings: number;
        deadline: Date;
        requirements: string;
        is_blocked: boolean;
        status: JobStatus;
        approvalStatus: JobApprovalStatus;
        rejectionReason: string | null;
        createdAt: Date;
        updatedAt: Date;
        applications: import("../applications/application.entity").Application[];
        views: import("./job-view.entity").JobView[];
        savedBy: import("./saved-job.entity").SavedJob[];
        jobSkills: import("./job-skill.entity").JobSkill[];
        reports: import("../reports/report.entity").Report[];
        history: JobHistory[];
    }>;
    updateJob(userId: string, id: string, dto: UpdateJobDto): Promise<Job | null>;
    updateJobStatus(userId: string, id: string, dto: UpdateJobStatusDto): Promise<Job | null>;
    deleteJob(userId: string, id: string): Promise<{
        message: string;
    }>;
    getMatchBySkills(userId: string): Promise<Job[]>;
    getMatchByMajor(userId: string): Promise<Job[]>;
    getRecommendedJobs(userId: string): Promise<Job[] | {
        data: {
            isExpired: boolean;
            id: string;
            employer: EmployerProfile;
            category: JobCategory;
            jobType: JobType;
            title: string;
            description: string;
            summary: string;
            benefits: string;
            imageUrl: string;
            location: string;
            latitude: number;
            longitude: number;
            salaryMin: number;
            salaryMax: number;
            currency: string;
            numberOfOpenings: number;
            deadline: Date;
            requirements: string;
            is_blocked: boolean;
            status: JobStatus;
            approvalStatus: JobApprovalStatus;
            rejectionReason: string | null;
            createdAt: Date;
            updatedAt: Date;
            applications: import("../applications/application.entity").Application[];
            views: import("./job-view.entity").JobView[];
            savedBy: import("./saved-job.entity").SavedJob[];
            jobSkills: import("./job-skill.entity").JobSkill[];
            reports: import("../reports/report.entity").Report[];
            history: JobHistory[];
        }[];
        meta: {
            totalItems: number;
            itemCount: number;
            itemsPerPage: number;
            totalPages: number;
            currentPage: number;
        };
    }>;
    private getEmployerProfileByUserId;
    private ensureEmployerOwnsJob;
    private assertJobRelationsExist;
    private assertJobStatusExists;
    private recordJobHistory;
    searchJobs(query: JobSearchDto): Promise<{
        data: {
            isExpired: boolean;
            id: string;
            employer: EmployerProfile;
            category: JobCategory;
            jobType: JobType;
            title: string;
            description: string;
            summary: string;
            benefits: string;
            imageUrl: string;
            location: string;
            latitude: number;
            longitude: number;
            salaryMin: number;
            salaryMax: number;
            currency: string;
            numberOfOpenings: number;
            deadline: Date;
            requirements: string;
            is_blocked: boolean;
            status: JobStatus;
            approvalStatus: JobApprovalStatus;
            rejectionReason: string | null;
            createdAt: Date;
            updatedAt: Date;
            applications: import("../applications/application.entity").Application[];
            views: import("./job-view.entity").JobView[];
            savedBy: import("./saved-job.entity").SavedJob[];
            jobSkills: import("./job-skill.entity").JobSkill[];
            reports: import("../reports/report.entity").Report[];
            history: JobHistory[];
        }[];
        meta: {
            totalItems: number;
            itemCount: number;
            itemsPerPage: number;
            totalPages: number;
            currentPage: number;
        };
    }>;
    searchJobsForAdmin(query: JobSearchDto): Promise<{
        data: {
            isExpired: boolean;
            id: string;
            employer: EmployerProfile;
            category: JobCategory;
            jobType: JobType;
            title: string;
            description: string;
            summary: string;
            benefits: string;
            imageUrl: string;
            location: string;
            latitude: number;
            longitude: number;
            salaryMin: number;
            salaryMax: number;
            currency: string;
            numberOfOpenings: number;
            deadline: Date;
            requirements: string;
            is_blocked: boolean;
            status: JobStatus;
            approvalStatus: JobApprovalStatus;
            rejectionReason: string | null;
            createdAt: Date;
            updatedAt: Date;
            applications: import("../applications/application.entity").Application[];
            views: import("./job-view.entity").JobView[];
            savedBy: import("./saved-job.entity").SavedJob[];
            jobSkills: import("./job-skill.entity").JobSkill[];
            reports: import("../reports/report.entity").Report[];
            history: JobHistory[];
        }[];
        meta: {
            totalItems: number;
            itemCount: number;
            itemsPerPage: number;
            totalPages: number;
            currentPage: number;
        };
    }>;
    exportJobsCsvForAdmin(query: JobSearchDto): Promise<string>;
}
