export declare enum NotificationType {
    JOB_APPROVED = "JOB_APPROVED",
    JOB_REJECTED = "JOB_REJECTED",
    APPLICATION_RECEIVED = "APPLICATION_RECEIVED",
    APPLICATION_ACCEPTED = "APPLICATION_ACCEPTED",
    APPLICATION_REJECTED = "APPLICATION_REJECTED",
    APPLICATION_INTERVIEW_SCHEDULED = "APPLICATION_INTERVIEW_SCHEDULED",
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
    PAYMENT_FAILED = "PAYMENT_FAILED",
    PROFILE_VERIFIED = "PROFILE_VERIFIED",
    PROFILE_REJECTED = "PROFILE_REJECTED",
    JOB_EXPIRING = "JOB_EXPIRING",
    NEW_REVIEW = "NEW_REVIEW",
    USER_SUSPENDED = "USER_SUSPENDED",
    JOB_APPLICATION_DEADLINE_APPROACHING = "JOB_APPLICATION_DEADLINE_APPROACHING",
    REPORT_CREATED = "REPORT_CREATED",
    REPORT_STATUS_CHANGED = "REPORT_STATUS_CHANGED"
}
