export declare enum ReportType {
    INAPPROPRIATE_CONTENT = "INAPPROPRIATE_CONTENT",
    SPAM = "SPAM",
    MISLEADING_INFORMATION = "MISLEADING_INFORMATION",
    DISCRIMINATION = "DISCRIMINATION",
    HARASSMENT = "HARASSMENT",
    SCAM = "SCAM",
    FAKE_JOB = "FAKE_JOB",
    UNDERPAID = "UNDERPAID",
    SAFETY_CONCERN = "SAFETY_CONCERN",
    OTHER = "OTHER"
}
